language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: QHj9IRwYJX0InwxjDQp13hjiEp0v3Z4igdCxAvIH5FAd0q9NfWxutdM49Vn7SmU/73dE75qNRp9vVMXKO646KnYQPFqNZLEBtlkskgnXSrc00/Zj3/WKSFg6EgjX1vO7+s+lBI8bLmbWIMmLZ+8CjMIrqRJoeHCL3DiENDU+iybJl+kEpHvJgWV3LVCo5NFF7EK5A4ygwEuUlJY341LXAiVcyFygsaI08rnARQaCjgw3L4K69FeL+G5GlvSes8ZNe2LZcSH4ZrN6+pOl3D2lk0utks0Q2K1IkioulOlBxzJdAOvJSZMlo9Hxkh7o+o+txI6payEPTudKpmF60QHhuBB083IkHddj7/OybJIsDoUS3DVthm67yhGdEUVwhjMStpZ2yp7+H6OtxkjsXTAPnyN2N9s3/QNxQEGEVwbOJSxXSxUaNX7pkkTo+3r+KF0R/4o2GM4bQ9kBbk8t5AGEIZAewnATmN2zxarQNjbIJ2Cy1ImSs2bQwda6QKsqiHqImVQofZ6hArH9vD0AP0ncP84LgYRJJnMSUrdQR8Hp00hcKtEE3lM2YNPBs5gWl0l6x7KpdedlcGwsqO9NWQlbFskWW/iIiom8DCkuQB4KnFp+RsEwd7kRy8Q0vXyPjTZaGChgth0vX1E0Oxlp3T3LTz09QH+hT+S0wtkMAXEJb4A=
  on:
    tags: true
    repo: IamAbbey/drf_compose
    python: 3.8
