language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: Ka+5uDNkcq6WMPCQBEdKCjUFAdYXtxIamlsBbrH1+0q3A5zyEAoNcEu+Pb1IK3WRyj9vV0fdNEy2m5jJNLvGb+WlrV+HNHQhriwZUTqJdyYL3oPZj6HOMrldhQoyijnh6GW5ri7xTqtwm+Z9nr2ZT64IwFDqn9L3HXWKacGYuaHitU/s/0r9oE6oojwr+dgYZ3MN8FnfNfmZ3hHdCSphOfR+1slgztRtqGWZJyUDtp+u3kvfxT+b6hxAZrwF/pv6ET56hmYvlSwNcb/57LSAfVZLq0wzzRjMipgCOUCO9lmmi+gZLOjMjnsTeFoMTOnNOENpzce9Bc80z5mg6DwDoeCFeKx5Hzd5JnMhR90r7G6U2kaO7ZjwneseO6tYqOyIU9vadJETZmQUUW3O2CYMU93TZUNjliPQiflIkR4dVqI36iYKxfZCJVX6BNpmPOoJa/acqFOp+lH9mtDpVyoXtjy7JUswvToWcx7EulB5h2jsBSVWeyjdKyocjjPsuOs5w8l8wtT2a6dkUJVmCmdH+VO/lnYve/dAMZ2rTqNQIQMYe5InayNw28MQou9B3FadeCZ0pHH+8FKCda9tm9oLnERfcbPcdbAMYH2ccb1oabw2fca5ibiHobtmTMoFc5cM/rp2FuamfYF3sJWSilGvL8rVoAcuanzSK8yTAXPBWdw=
  on:
    tags: true
    repo: IamAbbey/drf_compose
    python: 3.8
